### PR TITLE
add npmRun.sync() method

### PR DESCRIPTION
**Pull request by millermedeiros**
in some cases it's very useful to support the sync API (eg. build tools)

I'm planning to use this to implement the [`pipe` feature on esformatter](https://github.com/millermedeiros/esformatter/issues/168).

this saved me many hours of work! thanks for writing this tool.

### CODE REVIEW

**Comment by timoxley** [comment]
I think we should polyfill this for node 0.10.

**Comment by millermedeiros** [comment]
Thanks a lot! The polyfill was also a good idea. V0.10 is still widely used. Cheers

**Comment by timoxley** [comment]
:+1:

**Comment by timoxley** [comment]
I'll release new version shortly, going to improve error message when you try npm-run something that doesn't exist.

**Pull request merged**
